### ISSUE TITLE
Disable HTTPs?

### ISSUE THREAD

**Issue by eth0izzle** [eth0izzle/Needl#12]
As Needl's sole purpose is to generate random traffic so it _can_ be captured and stored, shall we disable HTTPs project wide? i.e when searching Google.

Thoughts?

**Comment by skos-ninja** [comment]
I feel like forcing using HTTP on what would typically be HTTPS would be an easy way for an ISP to pick out which traffic is fake and most of the storage of your browsing history by your ISP is really only ever the domain level as they are expecting HTTPS traffic.

**Comment by eth0izzle** [comment]
Fair point. Will close for now.
