### ISSUE TITLE
Simulate a web browser more effectively

### ISSUE THREAD

**Issue by eth0izzle** [eth0izzle/Needl#4]
When Needl requests a website (i.e. Google) it will download the requested URL only. We should make every effort to behave like a web browser by downloading any of the websites resources such as images, CSS and JavaScript files.

Should we consider using a headless browser testing framework such as PhantomJS?

**Comment by alexwilson** [comment]
Worth noting that it's now possible to run Chromium headlessly https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md

Potentially/optionally it might be worth using something like Selenium WebDriver to use real browsers - rotating those would further hurt attempts to profile based on individual asset download strategies. (Sadly a thing with HTTP2!)

**Comment by eth0izzle** [comment]
@antoligy I'm late to the party here but this is great - thanks! I've got more free time now so I plan to work on Needl and implement headless Chromium shortly

**Comment by eth0izzle** [comment]
headless Chrome now added!
